kmi/app/menu/__init__.py
# app/menu/__init__.py
from flask import Blueprint

menu = Blueprint('menu', __name__)

from . import routes

kmi/app/menu/routes.py
# app/menu/routes.py
from flask import render_template
from . import menu

@menu.route('/menu')
def menu():
    return render_template('menu.html')

kmi/app/profile/__init__.py
from flask import Blueprint

profile = Blueprint('profile', __name__)

from . import routes

kmi/app/profile/routes.py
from flask import render_template
from . import profile

@profile.route('/profile')
def view_profile():
    return render_template('profile.html')

kmi/app/settings/__init__.py
# app/settings/__init__.py
from flask import Blueprint

settings = Blueprint('settings', __name__)

from . import routes

kmi/app/settings/routes.py
# app/settings/routes.py
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from flask import render_template,request,jsonify,redirect,url_for
from . import settings 
true_labels = ['A','A','A','A','A','B','B','B','B','B','C','C','C','C','C']  # Etiquetas reales esperadas
cm_list = []
reporte = []
precision_global = []

@settings.route('/settings')
def ajustes():
    return render_template('settings.html')


@settings.route('/api-data')
def api_data():
    return render_template ('home.html')

        
@settings.route('/settings/save-responses', methods=['POST'])
def save_responses():
    try:
        user_responses = request.json.get('responses', [])  # Recibir las respuestas del frontend
        
        # Validación de longitud de respuestas
        if len(user_responses) != len(true_labels):
            return jsonify({'message': 'Cantidad de respuestas incorrecta'}), 400
        
        cm = confusion_matrix(true_labels, user_responses, labels=['A', 'B', 'C'])
        cm_list = cm.tolist()
        # Generar reporte de clasificación
        reporte = classification_report(true_labels, user_responses, labels=['A', 'B', 'C'], output_dict=True)
        # Calcular precisión global (accuracy)
        precision_global = accuracy_score(true_labels, user_responses)
    
        response = {'matriz':cm_list,
                    'reporte':reporte,
                    'global':precision_global}
        
        return jsonify(response)

        """
        # Calcular la matriz de confusión
        cm = confusion_matrix(true_labels, user_responses, labels=['A', 'B', 'C'])
        cm_list = cm.tolist()
        #print(cm_list)
        # Generar reporte de clasificación
        reporte = classification_report(true_labels, user_responses, labels=['A', 'B', 'C'], output_dict=True)
        #print(reporte)
        # Calcular precisión global (accuracy)
        precision_global = accuracy_score(true_labels, user_responses)
        #print(precision_global)
        # Devolver datos en formato JSON
        return redirect(url_for("settings.resultados"))
        """
    except Exception as e:
        print("Error al guardar respuestas:", e)
        return jsonify({'message': 'Error al guardar las respuestas', 'error': str(e)}), 500


@settings.route('/result', methods=['GET'])
def resultados():
    print(cm_list)
    datos = cm_list
    return render_template('result.html',data = datos)

kmi/app/tasks/__init__.py
# app/tasks/__init__.py
from flask import Blueprint

tasks = Blueprint('tasks', __name__)

from . import routes

kmi/app/tasks/routes.py
from flask import jsonify
from . import tasks
from . import globals

@tasks.route('/api-kmeans')
def datos():
    
    globals.processor.process_data()
    globals.processor.process_kmeans()
    globals.processor.process_results()

    v1, v2, v3 = globals.processor.get_cantPuntos()
    data = [
            { 'value': v1, 'name': 'CAT1' },
            { 'value': v2, 'name': 'CAT2' },
            { 'value': v3, 'name': 'CAT3' }
        ]
    
    chart = {
        'tooltip': {
            'trigger': 'item'
        },
        'legend': {
            'top': '5%',
            'left': 'center'
        },
        'series': [
            {
                'name': 'Result',
                'type': 'pie',
                'radius': ['30%', '70%'],
                'avoidLabelOverlap': False,
                'padAngle': 5,
                'itemStyle': {
                    'borderRadius': 10
                },
                'data': data
            }
        ]
    }

    cluster1,cluster2,cluster3 = globals.processor.get_coordenadas()
    data = [[0.056,-0.30],[-0.321, 0.134],[0.41, 0.258]]

    chart2 = {
        'tooltip': {
            'show':'true',
            'trigger':'item',
            'formatter': ' {a}<br/>{c0}'
        },
        'xAxis':
        {
            'scale': 'true'    
        },
        'yAxis': 
        {
            'scale': 'true'
        },
        'series': [
            {
            'name': 'Cluster: 1',
            'symbolSize': '8',
            'data': cluster1,
            'type': 'scatter',
            'color': '#5470c6'
            }
            ,
            {
            'name': 'Cluster: 2',
            'symbolSize': '8',
            'data': cluster2,
            'type': 'scatter',
            'color': '#91cc75'
            }
            ,
            {
            'name': 'Cluster: 3',
            'symbolSize': '8',
            'data': cluster3,
            'type': 'scatter',
            'color': '#fac858'
            },
            {
            'name': 'Centroids',
            'type': 'effectScatter',
            'symbolSize': '12',
            'data': data,
            'color':'#ee6666'
            }
        ]
    }

    dataset = globals.processor.get_tablaDesc()
    dataset = dataset.values.tolist()
    
    w1,w2,w3 = globals.processor.get_dataTabla()
    s1 = w1[:5]
    s2 = w2[:5]
    s3 = w3[:5]
    settings = s1+s2+s3
    # Preparar la respuesta JSON
    response = {
        'pie': chart,
        'scatter': chart2,
        'tabla' : dataset,
        'settings' : settings,
        'cluster1' : w1,
        'cluster2' : w2,
        'cluster3' : w3
    }
    
    return jsonify(response)
    

kmi/app/templates/base.html
<!-- app/templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js" integrity="sha256-6EJwvQzVvfYP78JtAMKjkcsugfTSanqe4WGFpUdzo88=" crossorigin="anonymous"></script>
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    {% block scripts %}
    <!-- Aquí se agregarán los scripts específicos de cada página -->
    {% endblock %}
</body>
</html>

kmi/app/templates/cat1.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>kummins</title>
        <!-- importacion de css -->
        <link href="{{ url_for('static',filename='css/styles.css') }}" rel="stylesheet" type="text/css">

        <!-- importacion de css -->
        <link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet" type="text/css">

        <!-- Incluir CSS de DataTables -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
   
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{{ url_for('menu.menu') }}">kummins</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
           
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ url_for('settings.ajustes') }}">Settings</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('profile.view_profile') }}">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">INICIO</div>
                            <a class="nav-link" href="{{ url_for('menu.menu') }}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                kummins DASHBOARD
                            </a>

                            <div class="sb-sidenav-menu-heading">RECURSOS</div>
                            <a class="nav-link" href="charts.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                GRAFICOS
                            </a>
                            <a class="nav-link" href="tables.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                TABLAS
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        kummins DASHBOARD
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="row">
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-primary text-white mb-4">
                                <div class="card-body">CATEGORIA A</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="{{ url_for('dash.cluster01') }}">BAJA-OBSOLETOS</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-warning text-white mb-4">
                                <div class="card-body">CATEGORIA B</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="{{ url_for('dash.cluster02') }}">CAMBIOS MODIFICACION</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-success text-white mb-4">
                                <div class="card-body">CATEGORIA C</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="{{ url_for('dash.cluster03') }}">BUEN ESTADO</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-fluid px-4">
                        <div class="row">
                            <div class="col-12 col-lg-8"> 
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-table me-1"></i>
                                        LISTADO DE EQUIPOS
                                    </div>
                                    <div class="card-body">
                                        <table id="tabla-valores" class="display">
                                            <tbody>
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-4"> 
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-pie me-1"></i>
                                        GRAFICO DE TORTA - CLUSTERS
                                    </div>
                                    <div class="card-body">
                                        <div class="chart-area">
                                          <div id="chartPie"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; kummins</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
                
        <!-- echarts grafico de burbuja -->   
        <script src="https://fastly.jsdelivr.net/npm/echarts-stat@latest/dist/ecStat.min.js"></script> 
        <!-- echarts grafico de burbuja y de torta -->
        <script src="https://fastly.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{url_for('static',filename='js/scripts.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <!-- Incluir jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <!-- Incluir JS de DataTables -->
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
        <script src="{{url_for('static',filename='js/cat1.js')}}"></script>
        <script src="{{url_for('static',filename='js/grafico.js')}}"></script>
        <script src="{{url_for('static',filename='js/pie.js')}}"></script>
        <!-- Script para inicializar DataTable -->
        
    </body>
</html>

kmi/app/templates/cat2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>kummins</title>
        <!-- importacion de css -->
        <link href="{{ url_for('static',filename='css/styles.css') }}" rel="stylesheet" type="text/css">

        <!-- importacion de css -->
        <link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet" type="text/css">

        <!-- Incluir CSS de DataTables -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
   
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{{ url_for('menu.menu') }}">kummins</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
           
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ url_for('settings.ajustes') }}">Settings</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('profile.view_profile') }}">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">INICIO</div>
                            <a class="nav-link" href="{{ url_for('menu.menu') }}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                kummins DASHBOARD
                            </a>

                            <div class="sb-sidenav-menu-heading">RECURSOS</div>
                            <a class="nav-link" href="charts.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                GRAFICOS
                            </a>
                            <a class="nav-link" href="tables.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                TABLAS
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        kummins DASHBOARD
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="row">
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-primary text-white mb-4">
                                <div class="card-body">CATEGORIA A</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="{{ url_for('dash.cluster01') }}">BAJA-OBSOLETOS</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-warning text-white mb-4">
                                <div class="card-body">CATEGORIA B</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="{{ url_for('dash.cluster02') }}">CAMBIOS MODIFICACION</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-success text-white mb-4">
                                <div class="card-body">CATEGORIA C</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="{{ url_for('dash.cluster03') }}">BUEN ESTADO</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container-fluid px-4">
                        <div class="row">
                            <div class="col-12 col-lg-8"> 
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-table me-1"></i>
                                        LISTADO DE EQUIPOS
                                    </div>
                                    <div class="card-body">
                                        <table id="tabla-valores2" class="display">
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-4"> 
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-pie me-1"></i>
                                        GRAFICO DE TORTA - CLUSTERS
                                    </div>
                                    <div class="card-body">
                                        <div class="chart-area">
                                          <div id="chartPie"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; kummins</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
                
        <!-- echarts grafico de burbuja -->   
        <script src="https://fastly.jsdelivr.net/npm/echarts-stat@latest/dist/ecStat.min.js"></script> 
        <!-- echarts grafico de burbuja y de torta -->
        <script src="https://fastly.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{url_for('static',filename='js/scripts.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <!-- Incluir jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <!-- Incluir JS de DataTables -->
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
        <script src="{{url_for('static',filename='js/cat2.js')}}"></script>
        <script src="{{url_for('static',filename='js/grafico.js')}}"></script>
        <script src="{{url_for('static',filename='js/pie.js')}}"></script>
        <!-- Script para inicializar DataTable -->
    </body>
</html>

kmi/app/templates/home.html
<!-- app/templates/home.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clustering de Datos</title>
    <!-- CSS de Bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- importacion de css -->
    <link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet" type="text/css">
    <style>
    
        body {
            margin: 0;
            background: url("{{ url_for('static', filename='img/background_final.png') }}") no-repeat center top;
            background-size: cover;
            height: 100vh;
        }
        header {
            position: absolute;
            top: 20px;
            left: 20px;
        }
        .logo {
            width: 100px;
        }
        
        h1 {
            font-size: 48px; /* Letra grande */
            font-weight: bold;
            text-align: left; /* Alineado a la izquierda */
            margin-left: 10%; /* Desde el medio hacia la izquierda */
            color: #003366; /* Azul oscuro elegante */
        }

        h2 {
            font-size: 24px; /* Letra más pequeña */
            font-weight: normal;
            text-align: left;
            margin-left: 10%;
            color:#6B8688; /* Gris sutil para contraste */
            max-width: 600px; /* Para que el texto no sea demasiado largo */
        }

    </style>
</head>
<body>
    
    <header>
        <img src="{{ url_for('static', filename='img/logo.png') }}" alt="Logo de la marca" class="logo">
    </header>

    <main>
        <section class="hero_container">
            <h1>Clustering de Datos Sin-Etiquetas</h1>
            <h2>kummins clasifica computadoras segun su hardware usando k-Means para una gestion eficiente.</h2>
            <div class="btn-container">
                <button class="start-button" onclick="startApp()">Iniciar</button>
            </div>
        </section>
       
    </main>
    <script src="{{ url_for('static', filename='js/home.js') }}"></script>
</body>    
</html>

kmi/app/templates/login.html
<!-- app/templates/login.html -->
{% extends "base.html" %}
{% block content %}
<div class="grid-container-login">
    <div class="login-box">
        <h2>Login</h2>
        <form method="POST">
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit">Login</button>
        </form>
    </div>
</div>
{% endblock %}

kmi/app/templates/menu.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu</title>
    <!-- Enlace a la biblioteca de iconos Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="menu">
        <a href="{{ url_for('dash.dashboard') }}"><i class="fas fa-tachometer-alt"></i> Dashboard</a>
        <a href="{{ url_for('settings.ajustes') }}"><i class="fas fa-cog"></i> Ajustes</a>
        <a href="#"><i class="fas fa-chart-line"></i> Informes IA</a>
        <a href="{{ url_for('dash.cluster01') }}"><i class="fas fa-cubes"></i> Categoria A</a>
        <a href="{{ url_for('dash.cluster02') }}"><i class="fas fa-cubes"></i> Categoria B</a>
        <a href="{{ url_for('dash.cluster03') }}"><i class="fas fa-cubes"></i> Categoria C</a>
    </div>
</body>
</html>

kmi/app/templates/profile.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil de Usuario</title>
    <link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet" type="text/css">
</head>
<body>
    <header>
        <h1>Perfil de Usuario</h1>
        <nav>
            <a href="{{ url_for('menu.menu') }}">Inicio</a>
            <a href="{{ url_for('auth.logout') }}">Cerrar Sesión</a>
        </nav>
    </header>
    <main>
        <section class="profile-info">
            <h2>Información del Perfil</h2>
            
        </section>
        
        
    </main>
    <footer>
        <p>&copy; 2024 Mi Aplicación</p>
    </footer>
</body>
</html>

kmi/app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Iniciar sesión</h1>
    <form action="{{ url_for('auth.login') }}" method="POST">
        <label for="username">Usuario:</label>
        <input type="text" id="username" name="username" required>
        <br>
        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Iniciar sesión</button>
    </form>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
</body>
</html>

kmi/app/templates/result.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Resultados</title>
</head>
<body>
    <h2>Resultados de la Clasificacion</h2>
    <ul>
        {% for item in data %}
            <li>{{ item }}</li>
        {% endfor %}
    </ul>
    
</body>
</html>